name: easacc_first_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.3
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^6.0.0
  shared_preferences: ^2.5.3
  webview_flutter: ^4.13.0
  flutter_bluetooth_serial: ^0.4.0
  multicast_dns: ^0.3.3
  network_info_plus: ^7.0.0
  logger: ^2.6.2
  freezed_annotation: ^3.1.0
  flutter_secure_storage: ^9.2.4
  internet_connection_checker_plus: ^2.7.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  freezed: ^3.2.3
  build_runner: ^2.4.14
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
