name: easacc_first_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.3
  # Social Login
  google_sign_in: ^7.0.2
  flutter_facebook_auth: ^6.0.0
  # Local Storage
  shared_preferences: ^2.4.1
  # WebView
  webview_flutter: ^4.13.0
  # Bluetooth
  flutter_blue_plus: ^2.0.2
  # mDNS Discovery
  multicast_dns: ^0.3.3
  # Connectivity
  connectivity_plus: ^7.0.0
  # Permission handling
  permission_handler: ^11.3.1
  # for beautified logging
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Custom Lint rules are a powerful way to improve the maintainability of a project
  custom_lint: ^0.8.0
  # A developer tool for users of Riverpod, designed to help stop common issues and simplify repetitive tasks.
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
