name: easacc_first_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.3
  # Social Login
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^6.0.0
  # Local Storage
  shared_preferences: ^2.5.3
  # WebView
  webview_flutter: ^4.13.0
  # Bluetooth
  flutter_blue_plus: ^2.0.2
  # mDNS Discovery
  multicast_dns: ^0.3.3
  # Connectivity
  connectivity_plus: ^7.0.0
  # Permission handling
  permission_handler: ^11.3.1
  # for beautified logging
  logger: ^2.6.2
  # Supabase
  supabase_flutter: ^2.10.3
  # For immutable data classes
  freezed_annotation: ^3.1.0
  # For secure storage
  flutter_secure_storage: ^9.2.4
  # To check your internet connection
  internet_connection_checker_plus: ^2.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Custom Lint rules are a powerful way to improve the maintainability of a project
  custom_lint: ^0.8.0
  # A developer tool for users of Riverpod, designed to help stop common issues and simplify repetitive tasks.
  riverpod_lint: ^3.0.3
  # For immutable data classes
  freezed: ^3.2.3
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.14
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
